config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  
  root 'static#home'
	
	get 'users/upload'      => 'users#upload'
  post 'users/crop'       => 'users#crop'
  get 'users/crop'        => 'users#crop'
  get 'users/remove'      => 'users#remove'
  get 'users/:id/friends', to: 'users#friends', as: 'friends'
	
	resources :users do 
		member do
			get 'lock_user'
			get 'unlock_user'
		end
	end
	
	resources :friendships, only: [:create, :destroy, :accept] do
		member do
			put :accept
		end
	end

	resources :posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "posts#upvote"
		end
	end

	resources :group_posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "group_posts#upvote"
		end
	end

	get 	'groups/:id/upload'				=> 'groups#upload', as: 'group_upload'
  post  'groups/:id/crop'   			=> 'groups#crop', as: 'group_crop'
  get		'groups/:id/crop'					=> 'groups#crop'
  get		'groups/:id/image_remove'	=> 'groups#image_remove', as: 'group_image_remove'

	get '/groups/your_groups' => 'groups#your_groups'

  get '/groups/:id/members/', to: 'groups#members', as: 'group_members'
  put '/groups/:group_id/members/make_admin/:request_id', to: 'group_members#make_admin', as: 'make_admin'
  put '/groups/:group_id/members/make_member/:request_id', to: 'group_members#make_member', as: 'make_member'
  put '/groups/:group_id/members/make_moderator/:request_id', to: 'group_members#make_moderator', as: 'make_moderator'
  delete '/groups/:group_id/members/reject/:request_id', to: 'group_members#reject_member', as: 'reject_member'
  delete '/groups/:group_id/members/ban/:user_id', to: 'group_members#ban_member', as: 'ban_member'

  put '/groups/:group_id/members/email_notify_on/:request_id', to: 'group_members#email_notify_on', as: 'email_notify_on'
  put '/groups/:group_id/members/email_notify_off/:request_id', to: 'group_members#email_notify_off', as: 'email_notify_off'


  resources :groups do
    resources :group_posts
    resources :group_members
  end

  resources :conversations do
  	resources :messages
 	end

	resources :subscriptions, only: [:create, :destroy]

	resources :activities, only: [:index]

	# Used for Stripe Subscriptions
	post '/charge/individual', to: 'charges#create_individual'
	post '/charge/individual_annual', to: 'charges#create_individual_annual'
	post '/charge/organization', to: 'charges#create_organization'
	post '/charge/organization_annual', to: 'charges#create_organization_annual'
	delete '/charge/cancel', to: 'charges#cancel_subscription'

	get 'contact', 				to: 'contact#new', as: 'contact'
	post 'contact', 			to: 'contact#create'

	post 'invite', 				to: 'invite#create'
	post 'group_invite', 	to: 'group_invite#create'

	#Admin Pages
	get 'admin'					=> 'admin#index'
	get 'admin/users'		=> 'admin#users'
	get 'admin/groups'	=> 'admin#groups'
	get 'admin/ads'			=> 'admin#ads'
	
	resources :advertisements

  # Static Pages
  get 'privacy' 	=> 'static#privacy'
  get 'terms'   	=> 'static#terms'
 	get 'faq' 			=> 'static#faq'
 	get 'advertise' => 'static#advertise'
 	get 'blocked' 	=> 'static#blocked'
 	get 'support' 	=> 'static#support'
 	get 'welcome' 	=> 'static#welcome'

 	get "*any", via: :all, to: "errors#not_found"

end

app/models/group_post.rb
# == Schema Information
#
# Table name: group_posts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  group_id   :integer
#  content    :text
#  post_type  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GroupPost < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	belongs_to :group

	validates :user_id, :presence => true
	validates :content, :presence => true



end

app/controllers/group_posts_controller.rb
class GroupPostsController < ApplicationController

	before_action :authenticate_user!
	before_action :set_group_post, only: [:edit, :update, :destroy, :upvote]

	def create
		@group = Group.find(params[:group_id])
		
		@group_post = current_user.group_posts.new(group_post_params)
		
		@group_post.group = @group

		if @group_post.save

			users = @group.group_members.where(email_notify: true).includes(:user)

			users.each do |user|
				ApplicationMailer.delay.send_group_prayer_request(current_user, @group_post, user.user) unless user.id == current_user.id
			end

			respond_to do |format|
				format.html {redirect_to group_path(@group), notice: "Group Post Created!"}
			end
		else
			redirect_to group_path(@group), notice: "You need to enter some text."
		end
	end

	def edit
	end

	def update
		if @group_post.update(group_post_params)
			respond_to do |format|
				format.html {redirect_to group_path(@group_post.group_id), notice: "Group Post Updated."}
			end
		else
			redirect_to post_path(@group_post), notice: "Something went wrong."
		end
	end

	def destroy
		@group_post.destroy
		respond_to do |format|
				format.html {redirect_to group_path(@group_post.group_id), notice: "Group Post Removed"}
			end
	end

	def upvote
	respond_to do |format|
		unless current_user.voted_for? @group_post 
			format.html { redirect_to :back }
			format.json { head :no_content }
			format.js { render :layout => false }
			@group_post.upvote_from current_user
		else
			format.html { redirect_to :back }
			format.json { head :no_content }
			format.js
		end
	end
end

	private

	def group_post_params
		params.require(:group_post).permit(:content, :post_type, :group_id)
	end

	def set_group_post
		@group_post = GroupPost.find(params[:id])
	end

end

app/views/group_posts/_edit_form.html.erb
<div id="js-add-post-form" class="ibox float-e-margins">
  <div class="ibox-content form-panel">
		<%= form_for(@group_post) do |f| %>
			<%= render 'partials/error_messages', object: f.object %>
			<div class="form-group">
				<%= f.text_area :content, placeholder: "Compose new group post...", :rows => "4", class: "form-control" %>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= f.select :post_type, [['Prayer Request', 'prayer'],['Praise Report', 'praise']], {}, {class: "form-control"}  %>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<a id="js-cancel-post-button" class="btn btn-white m-l-sm pull-right">Cancel</a>
						<%= f.button "Submit Group Post", class: "btn btn-primary pull-right", data: {disable_with: "<i class='fa fa-fw fa-spinner fa-spin'></i> Posting"} %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/group_posts/_form.html.erb
<% if current_user.subscribed == true %>
<%# Community supporter, so 800 characters per post %>
<div id="js-add-post-form" class="ibox float-e-margins">
<div class="ibox-title">
	<h5>Create A Group Post</h5>
   <span class="pull-right"><div class="grey-text" id="charNum">800 characters left</div>
</span>
</div>
  <div class="ibox-content form-panel">
		<%= form_for(@group_post) do |f| %>
			<%= render 'partials/error_messages', object: f.object %>
			<div class="form-group">
				<%= f.text_area :content, placeholder: "Compose new group post...", :rows => "4", class: "form-control post-content", id: "field", maxlength: "800" %>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= f.select :post_type, [['Prayer Request', 'prayer'],['Praise Report', 'praise']], {}, {class: "form-control"}  %>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<%= hidden_field_tag :group_id, @group.id %>
						<a id="js-cancel-post-button" class="btn btn-white m-l-sm pull-right">Cancel</a>
						<%= f.button "Submit Group Post", class: "btn btn-primary pull-right", data: {disable_with: "<i class='fa fa-fw fa-spinner fa-spin'></i> Posting"} %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>
<script>
$('#field').keyup(function () {
  var max = 800;
  var len = $(this).val().length;
  if (len >= max) {
    $('#charNum').html('<span style="color: #F00;">0  characters left</span>');
  } else {
    var char = max - len;
    $('#charNum').text(char + ' characters left');
  };
});
</script>
<% else %>
<%# Not a community supporter, so only 600 characters per post %>
<div id="js-add-post-form" class="ibox float-e-margins">
<div class="ibox-title">
	<h5>Create A Group Post</h5>
   <span class="pull-right"><div class="grey-text" id="charNum">600 characters left</div>
</span>
</div>
  <div class="ibox-content form-panel">
		<%= form_for(@group_post) do |f| %>
			<%= render 'partials/error_messages', object: f.object %>
			<div class="form-group">
				<%= f.text_area :content, placeholder: "Compose new group post...", :rows => "4", class: "form-control post-content", id: "field", maxlength: "600" %>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= f.select :post_type, [['Prayer Request', 'prayer'],['Praise Report', 'praise']], {}, {class: "form-control"}  %>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<%= hidden_field_tag :group_id, @group.id %>
						<a id="js-cancel-post-button" class="btn btn-white m-l-sm pull-right">Cancel</a>
						<%= f.button "Submit Group Post", class: "btn btn-primary pull-right", data: {disable_with: "<i class='fa fa-fw fa-spinner fa-spin'></i> Posting"} %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>
<script>
$('#field').keyup(function () {
  var max = 600;
  var len = $(this).val().length;
  if (len >= max) {
    $('#charNum').html('<span style="color: #F00;">0 characters left</span>');
  } else {
    var char = max - len;
    $('#charNum').text(char + ' characters left');
  };
});
</script>
<% end %>

<script type="text/javascript">
$(document).ready(function() { 
	$("#js-add-post-form").hide();
});

	$("#js-add-post-button").click(function(){
    $("#js-add-post-form").slideDown("slow");
});

	$("#js-cancel-post-button").click(function(){
    $("#js-add-post-form").slideUp("slow");
});
</script>

app/views/group_posts/_group_post.html.erb
<div id="group-post-<%= group_post.id %>" class="social-feed-box">
	<% if group_post.user == current_user %>
		<%# Poster Is Current User %>
		<div class="pull-right dropdown">
			<button class="dropdown-toggle btn-white" data-toggle="dropdown" aria-expanded="false">
				<i class="fa fa-angle-down"></i>
			</button>
			<ul class="dropdown-menu m-t-xs">
				<li>
					<%= link_to edit_group_post_path(group_post) do %>
						<i class="fa fa-pencil-square-o fa-fw"></i> Edit Post
					<% end %>
				</li>
				<li>
					<%= link_to group_post_path(group_post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do %>
						<i class="fa fa-trash-o fa-fw"></i> Delete Post
					<% end %>
				</li>
			</ul>
		</div>
	<% else %>
		<%# Poster Is NOT Current User %>
		<% if current_user.voted_for? group_post %>
			<div class="pull-right">
				<span class="btn-prayed-for btn-circle" data-toggle="tooltip" data-placement="left" title="You've already prayed for this">
					<i class="fa fa-heart fa-fw"></i>
				</span>
			</div>
	  <% else %>
			<div class="pull-right btn-prayed-for-<%= group_post.id %>">
				<%= link_to prayed_group_post_path(group_post), :remote => true, method: :put, class: 'js-not-prayed-btn btn-pray-for btn-circle' do %>
						<i class="fa fa-heart fa-fw"></i>
				<% end %>
			</div>
		<% end %>
	<% end %>

	<% if (current_user.admin_this_group?(@group) || current_user.moderate_this_group?(@group)) && current_user != group_post.user %>
		<div class="pull-right dropdown m-r-sm">
			<button class="dropdown-toggle btn-white" data-toggle="dropdown" aria-expanded="false">
				Admin <i class="fa fa-angle-down"></i>
			</button>
			<ul class="dropdown-menu m-t-xs">
				<li>
					<%= link_to group_post_path(group_post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do  %>
						<i class="fa fa-trash-o fa-fw"></i> Delete Post
					<% end %>
				</li>
				<li>
					<%= link_to ban_member_path(@group, group_post.user.id), method: :delete, data: { confirm: 'Are you sure you want to delete this group member?', :'confirm-button-text' => 'Delete', :'cancel-button-text' => 'Cancel', :'confirm-button-color' => '#EFA039'} do  %>
						<i class="fa fa-ban fa-fw"></i> Remove User
					<% end %>
				</li>
			</ul>
		</div>
	<% end %>

		<div class="pull-left">
			<% if group_post.user.avatar.present? %>
				<%= image_tag(group_post.user.avatar_url(:friendship), class: "img-rounded grey-border") %>
			<% else %>
				<div class="default-friendship-icon <%= color_length(group_post.user.first_name.length) %>"><%= group_post.user.first_name.chars.first.titlecase + group_post.user.last_name.chars.first.titlecase %></div>
			<% end %>
		</div>
		<div class="social-body">
			<%= link_to user_path(group_post.user.username) do %>
				<strong><%= group_post.user.first_name.titlecase + " " + group_post.user.last_name.titlecase %></strong>
			<% end %>
			<br />
			<small class="text-muted">
				<% if group_post.post_type == 'prayer' %>
					<span class="prayer-label">Prayer Request</span>
				<% else %>
					<span class="praise-label">Praise Report</span>
				<% end %>
				<span class="dash">/</span> <%= time_ago_in_words(group_post.created_at) %> ago <span class="dash">/</span> Prayed for <span class="prayer-count-for-<%= group_post.id %>"><%= pluralize(group_post.get_upvotes.size, 'time') %></span></small>
    <p class="m-t-xs"><%= group_post.content %></p>
    </div>
	
</div>

app/views/group_posts/edit.html.erb
<div class="row wrapper page-heading m-b-lg">
	<div class="container">
		<div class="col-lg-12">
			<h2>Edit Post</h2>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-9">
			<%= render 'edit_form' %>
		</div>
</div>

app/views/group_posts/upvote.js.erb
$('.js-not-prayed-btn').bind('ajax:success', function() { 
	$('.btn-prayed-for-<%= @group_post.id %>').html('<span class="btn-prayed-for btn-circle"  data-toggle="tooltip" data-placement="left" title="You\'ve already prayed for this"><i class="fa fa-heart fa-fw"></i></span>');
	$('.prayer-count-for-<%= @group_post.id %>').html('<%= j pluralize(@group_post.get_upvotes.size, "time") %>');

toastr.options = {
	closeButton: true,
  progressBar: true,
  preventDuplicates: true,
  showMethod: 'slideDown',
  timeOut: 3000
};
toastr.success('','Marked as Prayed For');

});