config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  
  root 'static#home'
	
	get 'users/upload'      => 'users#upload'
  post 'users/crop'       => 'users#crop'
  get 'users/crop'        => 'users#crop'
  get 'users/remove'      => 'users#remove'
  get 'users/:id/friends', to: 'users#friends', as: 'friends'
	
	resources :users do 
		member do
			get 'lock_user'
			get 'unlock_user'
		end
	end
	
	resources :friendships, only: [:create, :destroy, :accept] do
		member do
			put :accept
		end
	end

	resources :posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "posts#upvote"
		end
	end

	resources :group_posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "group_posts#upvote"
		end
	end

	get 	'groups/:id/upload'				=> 'groups#upload', as: 'group_upload'
  post  'groups/:id/crop'   			=> 'groups#crop', as: 'group_crop'
  get		'groups/:id/crop'					=> 'groups#crop'
  get		'groups/:id/image_remove'	=> 'groups#image_remove', as: 'group_image_remove'

	get '/groups/your_groups' => 'groups#your_groups'

  get '/groups/:id/members/', to: 'groups#members', as: 'group_members'
  put '/groups/:group_id/members/make_admin/:request_id', to: 'group_members#make_admin', as: 'make_admin'
  put '/groups/:group_id/members/make_member/:request_id', to: 'group_members#make_member', as: 'make_member'
  put '/groups/:group_id/members/make_moderator/:request_id', to: 'group_members#make_moderator', as: 'make_moderator'
  delete '/groups/:group_id/members/reject/:request_id', to: 'group_members#reject_member', as: 'reject_member'
  delete '/groups/:group_id/members/ban/:user_id', to: 'group_members#ban_member', as: 'ban_member'

  put '/groups/:group_id/members/email_notify_on/:request_id', to: 'group_members#email_notify_on', as: 'email_notify_on'
  put '/groups/:group_id/members/email_notify_off/:request_id', to: 'group_members#email_notify_off', as: 'email_notify_off'


  resources :groups do
    resources :group_posts
    resources :group_members
  end

  resources :conversations do
  	resources :messages
 	end

	resources :subscriptions, only: [:create, :destroy]

	resources :activities, only: [:index]

	# Used for Stripe Subscriptions
	post '/charge/individual', to: 'charges#create_individual'
	post '/charge/individual_annual', to: 'charges#create_individual_annual'
	post '/charge/organization', to: 'charges#create_organization'
	post '/charge/organization_annual', to: 'charges#create_organization_annual'
	delete '/charge/cancel', to: 'charges#cancel_subscription'

	get 'contact', 				to: 'contact#new', as: 'contact'
	post 'contact', 			to: 'contact#create'

	post 'invite', 				to: 'invite#create'
	post 'group_invite', 	to: 'group_invite#create'

	#Admin Pages
	get 'admin'					=> 'admin#index'
	get 'admin/users'		=> 'admin#users'
	get 'admin/groups'	=> 'admin#groups'
	get 'admin/ads'			=> 'admin#ads'
	
	resources :advertisements

  # Static Pages
  get 'privacy' 	=> 'static#privacy'
  get 'terms'   	=> 'static#terms'
 	get 'faq' 			=> 'static#faq'
 	get 'advertise' => 'static#advertise'
 	get 'blocked' 	=> 'static#blocked'
 	get 'support' 	=> 'static#support'
 	get 'welcome' 	=> 'static#welcome'

 	get "*any", via: :all, to: "errors#not_found"

end

app/views/admin/_ads_table.html.erb
<div class="ibox float-e-margins m-t-md">
	<div class="ibox-title">
		<div class="col-md-6"><h4>Advertising</h4></div>
		<div class="col-md-6">
		<%= link_to new_admin_ad_path, class: 'btn btn-primary btn-sm pull-right' do %>
			<i class="fa fa-plus fa-fw"></i> Add Ad
		<% end %>
		</div>
	</div>
	<div class="ibox-content">
		<table class="table">
			<thead>
				<tr>
					<th>Title</th>
					<th>Text</th>
					<th>Link Text</th>
					<th>Created</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<% @advertisements.each do |ad| %>
				<tr class="<%= cycle('even', 'odd') %>">
					<td><%= ad.title %></td>
					<td><%= truncate(ad.content, length: 40, omission: '...') %></td>
					<td><a href="<%= ad.link %>" target="_blank"><%= ad.link_text %></a></td>
					<td><%= time_ago_in_words(ad.created_at) %> ago</td>
					<td>
					<div class="btn-group pull-right">
						<%= link_to "Edit", root_path, class: "btn btn-xs btn-primary" %><%= link_to "Delete", root_path, class: "btn btn-xs btn-gold" %>
						</div>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/_groups_table.html.erb
<div class="ibox float-e-margins m-t-md">
	<div class="ibox-title">
		<h4>Groups</h4>
	</div>
	<div class="ibox-content">
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>Name</th>
					<th>Privacy</th>
					<th>Members</th>
					<th>Created</th>
				</tr>
			</thead>
			<tbody>
			<% @groups.each do |group| %>
				<tr class="<%= cycle('even', 'odd') %>">
					<td>
						<% if group.image.present? %>
			        <%= image_tag(group.image_url(:navigation), class: "img-rounded grey-border") %>
			        <% else %>
			        <div class="default-navigation-icon <%= color_length(group.name.length) %> "><i class="fa fa-users fa-fw"></i></div>
		        <% end %>
					</td>
					<td><%= link_to group_path(group) do %><%= group.name %><% end %><br /><span class="text-muted"><small><%= group.organization %><% if group.organization.present? && group.location.present? %> / <% end %> <%= group.location %></small></span></td>
					<td><%= group.privacy %></td>
					<td><%= group.group_members.count %></td>
					<td><%= time_ago_in_words(group.created_at) %> ago</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/_menu.html.erb
	<div class="ibox float-e-margins">
		<div class="ibox-content">
		<%= link_to "Statistics", admin_path, class: "m-r-sm" %>
		<span class="m-r-sm">/</span> 
		<%= link_to "Users", admin_users_path, class: "m-r-sm" %>
		<span class="m-r-sm">/</span> 
		<%= link_to "Groups", admin_groups_path, class: "m-r-sm" %>
		<span class="m-r-sm">/</span> 
		<%= link_to "Advertisements", advertisements_path %>
		</div>
	</div>

app/views/admin/_users_table.html.erb
<div class="ibox float-e-margins m-t-md">
	<div class="ibox-title">
		<h4>Users</h4>
	</div>
	<div class="ibox-content">
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>Name</th>
					<th>Username</th>
					<th>Location</th>
					<th>Friends</th>
					<th>Posts</th>
					<th>Supporter</th>
					<th>Last Signed In</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
			<% @users.each do |user| %>
				<tr class="<%= cycle('even', 'odd') %>">
					<td>
						<% if user.avatar.present? %>
			        <%= image_tag(user.avatar_url(:navigation), class: "img-rounded grey-border") %>
			        <% else %>
			        <div class="default-navigation-icon <%= color_length(user.first_name.length) %>"><%= user.first_name.chars.first + user.last_name.chars.first %></div>
		        <% end %>
					</td>
					<td><%= user.first_name + " " + user.last_name %></td>
					<td><%= link_to user.username, user_path(user.username) %></td>
					<td>
						<% if user.city.present? && user.state.present? %>
							<%= user.city %>, <%= user.state %>
						<% else %>
							<%= user.city %> <%= user.state %>
						<% end %>
					</td>
					<td>
						<%= user.active_friends.count %>
					</td>
					<td>
						<%= user.posts.count + user.group_posts.count %>
					</td>
					<td>
						<%= user.subscription_plan %>
					</td>
					<td>
						<%  if user.current_sign_in_at %>
						<%= time_ago_in_words(user.current_sign_in_at) %> ago
						<% else %>
							Never
						<% end %>
						</td>
					<td>
						<%= user.status %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/ads.html.erb
<div class="row wrapper border-bottom page-heading m-b-lg">
  <div class="container">
  	<div class="row">
	    <div class="col-lg-12">
	      <h2>Advertising Administration</h2>
	    </div>
	  </div>
  </div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= render 'menu' %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render 'ads_table' %>
			<%= paginate @advertisements %>
		</div>
	</div>
</div>

app/views/admin/groups.html.erb
<div class="row wrapper border-bottom page-heading m-b-lg">
  <div class="container">
  	<div class="row">
	    <div class="col-lg-12">
	      <h2>Group Administration</h2>
	    </div>
	   </div>
  </div>
</div>
<div class="container">
		<div class="row">
		<div class="col-md-12">

			<%= render 'menu' %>

		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render 'groups_table' %>
			<%= paginate @groups %>
		</div>
	</div>
</div>

app/views/admin/index.html.erb
<div class="row wrapper border-bottom page-heading m-b-lg">
  <div class="container">
  	<div class="row">
	    <div class="col-lg-12">
	      <h2>Site Statistics</h2>
	    </div>
	   </div>
  </div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			
			<%= render 'menu' %>

		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="row m-b-md">
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-user fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Total Members </span>
								<h2 class="font-bold teal"><%= number_with_delimiter(@user_count, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-users fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Total Groups</span>
								<h2 class="font-bold"><%= number_with_delimiter(@group_count, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-pencil fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Total Posts </span>
								<h2 class="font-bold"><%= number_with_delimiter(@post_count, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-heart fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Total Prayers </span>
								<h2 class="font-bold"><%= number_with_delimiter(@prayed_count, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
			</div>
			<div class="row m-b-md">
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-hourglass-o fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Monthly Individuals</span>
								<h2 class="font-bold teal"><%= number_with_delimiter(@monthly_individuals, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-calendar fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Annual Individuals</span>
								<h2 class="font-bold"><%= number_with_delimiter(@annual_individuals, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-hourglass-o fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Monthly Organizations </span>
								<h2 class="font-bold"><%= number_with_delimiter(@monthly_organizations, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="widget style2 white-bg grey-border">
							<i class="fa fa-calendar fa-4x pull-left blue-text"></i>
							<div class="text-right">
								<span> Annual Organizations</span>
								<h2 class="font-bold"><%= number_with_delimiter(@annual_organizations, :delimiter => ',') %></h2>
							</div>
						</div>
					</div>
			</div>			
			<div class="row">
				<div class="col-md-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<span class="blue-text"><strong>New Sign Ups</strong></span>
						</div>
						<div class="ibox-content">
							Past Hour<span class="pull-right"><%= number_with_delimiter(@new_hour, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Day<span class="pull-right"><%= number_with_delimiter(@new_day, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Month<span class="pull-right"><%= number_with_delimiter(@new_month, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Year<span class="pull-right"><%= number_with_delimiter(@new_year, :delimiter => ',') %></span>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<span class="blue-text"><strong>Active Users</strong></span>
						</div>
						<div class="ibox-content">
							Past Hour<span class="pull-right"><%= number_with_delimiter(@hour, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Day<span class="pull-right"><%= number_with_delimiter(@day, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Month<span class="pull-right"><%= number_with_delimiter(@month, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Year<span class="pull-right"><%= number_with_delimiter(@year, :delimiter => ',') %></span>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<span class="blue-text"><strong>New Groups</strong></span>
						</div>
						<div class="ibox-content">
							Past Hour<span class="pull-right"><%= number_with_delimiter(@new_groups_hour, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Day<span class="pull-right"><%= number_with_delimiter(@new_groups_day, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Month<span class="pull-right"><%= number_with_delimiter(@new_groups_month, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Year<span class="pull-right"><%= number_with_delimiter(@new_groups_year, :delimiter => ',') %></span>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<span class="blue-text"><strong>New Posts</strong></span>
						</div>
						<div class="ibox-content">
							Past Hour<span class="pull-right"><%= number_with_delimiter(@new_posts_hour, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Day<span class="pull-right"><%= number_with_delimiter(@new_posts_day, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Month<span class="pull-right"><%= number_with_delimiter(@new_posts_month, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Year<span class="pull-right"><%= number_with_delimiter(@new_posts_year, :delimiter => ',') %></span>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<span class="blue-text"><strong>Prayers</strong></span>
						</div>
						<div class="ibox-content">
							Past Hour<span class="pull-right"><%= number_with_delimiter(@prayed_hour, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Day<span class="pull-right"><%= number_with_delimiter(@prayed_day, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Month<span class="pull-right"><%= number_with_delimiter(@prayed_month, :delimiter => ',') %></span>
							<hr class="m-small">
							Past Year<span class="pull-right"><%= number_with_delimiter(@prayed_year, :delimiter => ',') %></span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/users.html.erb
<div class="row wrapper border-bottom page-heading m-b-lg">
  <div class="container">
  	<div class="row">
	    <div class="col-lg-12">
	      <h2>User Administration</h2>
	    </div>
	  </div>
  </div>
</div>
<div class="container">
		<div class="row">
		<div class="col-md-12">
			
			<%= render 'menu' %>
		
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
				<%= render 'users_table' %>
				<%= paginate @users %>
		</div>
	</div>
</div>