config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  
  root 'static#home'
	
	get 'users/upload'      => 'users#upload'
  post 'users/crop'       => 'users#crop'
  get 'users/crop'        => 'users#crop'
  get 'users/remove'      => 'users#remove'
  get 'users/:id/friends', to: 'users#friends', as: 'friends'
	
	resources :users do 
		member do
			get 'lock_user'
			get 'unlock_user'
		end
	end
	
	resources :friendships, only: [:create, :destroy, :accept] do
		member do
			put :accept
		end
	end

	resources :posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "posts#upvote"
		end
	end

	resources :group_posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "group_posts#upvote"
		end
	end

	get 	'groups/:id/upload'				=> 'groups#upload', as: 'group_upload'
  post  'groups/:id/crop'   			=> 'groups#crop', as: 'group_crop'
  get		'groups/:id/crop'					=> 'groups#crop'
  get		'groups/:id/image_remove'	=> 'groups#image_remove', as: 'group_image_remove'

	get '/groups/your_groups' => 'groups#your_groups'

  get '/groups/:id/members/', to: 'groups#members', as: 'group_members'
  put '/groups/:group_id/members/make_admin/:request_id', to: 'group_members#make_admin', as: 'make_admin'
  put '/groups/:group_id/members/make_member/:request_id', to: 'group_members#make_member', as: 'make_member'
  put '/groups/:group_id/members/make_moderator/:request_id', to: 'group_members#make_moderator', as: 'make_moderator'
  delete '/groups/:group_id/members/reject/:request_id', to: 'group_members#reject_member', as: 'reject_member'
  delete '/groups/:group_id/members/ban/:user_id', to: 'group_members#ban_member', as: 'ban_member'

  put '/groups/:group_id/members/email_notify_on/:request_id', to: 'group_members#email_notify_on', as: 'email_notify_on'
  put '/groups/:group_id/members/email_notify_off/:request_id', to: 'group_members#email_notify_off', as: 'email_notify_off'


  resources :groups do
    resources :group_posts
    resources :group_members
  end

  resources :conversations do
  	resources :messages
 	end

	resources :subscriptions, only: [:create, :destroy]

	resources :activities, only: [:index]

	# Used for Stripe Subscriptions
	post '/charge/individual', to: 'charges#create_individual'
	post '/charge/individual_annual', to: 'charges#create_individual_annual'
	post '/charge/organization', to: 'charges#create_organization'
	post '/charge/organization_annual', to: 'charges#create_organization_annual'
	delete '/charge/cancel', to: 'charges#cancel_subscription'

	get 'contact', 				to: 'contact#new', as: 'contact'
	post 'contact', 			to: 'contact#create'

	post 'invite', 				to: 'invite#create'
	post 'group_invite', 	to: 'group_invite#create'

	#Admin Pages
	get 'admin'					=> 'admin#index'
	get 'admin/users'		=> 'admin#users'
	get 'admin/groups'	=> 'admin#groups'
	get 'admin/ads'			=> 'admin#ads'
	
	resources :advertisements

  # Static Pages
  get 'privacy' 	=> 'static#privacy'
  get 'terms'   	=> 'static#terms'
 	get 'faq' 			=> 'static#faq'
 	get 'advertise' => 'static#advertise'
 	get 'blocked' 	=> 'static#blocked'
 	get 'support' 	=> 'static#support'
 	get 'welcome' 	=> 'static#welcome'

 	get "*any", via: :all, to: "errors#not_found"

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id           :integer          not null, primary key
#  name         :string
#  organization :string
#  location     :string
#  description  :text
#  privacy      :string
#  image        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Group < ActiveRecord::Base
	mount_uploader :image, GroupUploader
	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_image


	has_many :group_members, dependent: :destroy
	has_many :members, through: :group_members, source: :user

	has_many :group_posts, dependent: :destroy

	validates :name, :presence => { :message => " cannot be blank" }
	validates :name, length: {
    minimum: 5,
    maximum: 50,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
  }

	include PgSearch
  pg_search_scope :search, against: [:name, :location, :organization]

	def admins
		members.includes(:group_members).where('group_members.role = ?', 'admin')
	end

	def moderators
		members.includes(:group_members).where('group_members.role = ?', 'moderator')
	end

	def regular_users
		members.includes(:group_members).where('group_members.role = ?', 'member')
	end

	def private?
		self.privacy == 'Private'
	end

	def subscribers
    group_members.where(email_notify: true)
  end

# Cropping ===========================

  def crop_image
    image.recreate_versions! if crop_x.present?
  end

# Search ===========================

def self.text_search(query)
	if query.present?
		search(query)
	else
		order("created_at DESC")
  end
end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :evaluate_role, only: [:members]
  before_filter :set_group, only: [:edit, :upload, :show, :members, :update, :crop, :image_remove, :destroy]

  def index
    @groups = Group.text_search(params[:query]).order("created_at DESC").page(params[:page]).per(10)
    @advertisements = Advertisement.limit(3).order("RANDOM()")
    @count = current_user.group_members.where(role: "admin").count + current_user.group_members.where(role: "moderator").count + current_user.group_members.where(role: "member").count
    @member_level = current_user.subscription_plan
  end 

  def new
    @group = Group.new
    @user = current_user
    @count = current_user.group_members.where(role: "admin").count + current_user.group_members.where(role: "moderator").count
  end

  def create
    @count = current_user.group_members.where(role: "admin").count + current_user.group_members.where(role: "moderator").count
    @group = current_user.groups.build(group_params)
    if @group.save
      gm = GroupMember.new
      gm.user_id = current_user.id
      gm.group = @group
      gm.role = "admin"
      gm.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    if current_user.admin_this_group?(@group)
      
    else 
      redirect_to groups_path
    end
  end

  def upload

  end

  def show
    @group_invite = GroupInvite.new
    @group_post = GroupPost.new
    @group_posts = @group.group_posts.order('created_at DESC').page(params[:page]).per(10)
    @members = @group.group_members.where(role: "member")
    @owners = @group.group_members.where(role: "admin")
    @advertisements = Advertisement.limit(3).order("RANDOM()")
    if current_user
      @current_member = current_user.group_members.find_by(group_id: @group.id)
    end

  end

  # Possible roles in decending order: admin, moderator, member, pending, blocked

  def your_groups
    @advertisements = Advertisement.limit(3).order("RANDOM()")
    @admin = current_user.group_members.where(role: "admin")
    @moderator = current_user.group_members.where(role: "moderator")
    @member = current_user.group_members.where(role: "member")
    @requests = current_user.group_members.where(role: "pending")
  end

  def members
    @admins = @group.group_members.where(role: 'admin')
    @moderators = @group.group_members.where(role: 'moderator')
    @pending = @group.group_members.where(role: 'pending')
    @members = @group.group_members.where(role: 'member')
    
    if current_user
      @current_member = current_user.group_members.find_by(group_id: @group.id)
    end

  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html {
          if params[:group][:image].present?
            redirect_to group_crop_path(@group)
          else
            # Delete Large upload after User makes crop selection 
              File.delete @group.image.path if File.exists?(@group.image.path)
            redirect_to edit_group_path, notice: "Group was successfully updated."
          end
        }
        format.json { render :show, status: :ok, location: @group }
    else
      format.html { redirect_to group_upload_path }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

  def crop

  end

  def image_remove
    @group.remove_image!
    @group.save
    redirect_to edit_group_path, notice: "Image was successfully removed."
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: "Group Deleted."
  end

  private

  def group_params
    params.require(:group).permit(:name, :organization, :location, :description, :privacy, :image, :crop_x, :crop_y, :crop_w, :crop_h)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def evaluate_role
    gm = GroupMember.find_by(user_id: current_user.id,  group_id: params[:id])
    if gm == nil || gm.role == 'pending' || gm.role == 'blocked'
      redirect_to group_path(params[:id])
    end
  end

end

app/views/groups/_group.html.erb
  <div class="group-row <%= cycle('even', 'odd') -%>">
    <div class="col-sm-8">
      <div class="pull-left">
        <%= link_to group_path(group) do %>
          <% if group.image.friendship.present? %>
            <%= image_tag(group.image_url(:friendship), class: "img-rounded grey-border") %>
          <% else %>
            <div class="default-friendship-icon <%= color_length(group.name.length) %> "><i class="fa fa-users fa-fw font-awesome-friendship-icon"></i></div>
          <% end %>
        <% end %>
      </div>
      <div class="search-body">
        <div class="name m-t-xs">
          <%= link_to group_path(group) do %>
            <%= group.name %>
          <% end %>
        </div>
        <div class="location m-b-xs">
          <% if group.organization.present? %>
            <%= group.organization %>
            <% if group.location.present? %>
              <span class="dash">/</span>
            <% end %>
          <% end %>
          <% if group.location.present? %>
            <%= group.location %>
          <% end %>
            <span class="dash">/</span>
            <%= pluralize((group.regular_users.count + group.moderators.count + group.admins.count), 'Member') %>
            <span class="dash">/</span>
            <% if group.privacy == "Private" %>
              Private Group
            <% else %>
              Public Group
            <% end %>
        </div>
      </div>
    </div>
      <div class="col-sm-4">
        <% if current_user %>
          <span class="pull-right m-t-sm action-button-for-<%= group.id %>">
            <%= link_to 'Show', group_path(group), class: "btn btn-white btn-sm" %>
            <% if current_user.admin_this_group?(group) || current_user.moderate_this_group?(group) %>
              <%= link_to 'Manage Members', group_members_path(group), class: "btn btn-white btn-sm" %>
            <% end %>
          </span>
        <% end %>
      </div>
          <div class="clearfix"></div>
  </div>

app/views/groups/_group_box.html.erb
<!-- Start Group Box -->
<div class="ibox float-e-margins">
  <div class="ibox-content user-panel">
    <div class="pull-left">
			<% if @group.image.profile.present? %>
				<%= image_tag(@group.image_url(:profile), class: "img-rounded grey-border") %>
			<% else %>
				<div class="default-profile-icon <%= color_length(@group.name.length) %> grey-border"><i class="fa fa-users fa-fw font-awesome-profile-icon"></i></div>
			<% end %>
		</div>
		<div class="media-body">
      <div class="media-name">
      	<%= @group.name %>
      </div>
      <div class="media-location m-b-xs">
        <small class="text-muted">
 
					<% if @group.organization.present? %>
						<%= @group.organization %><br />
					<% end %>
					<% if @group.location.present? %>
						<%= @group.location %>
					<% end %>
				
				</small>
			</div>
		</div>
		</div>
			<% if @group.description.present? %>
			<div class="ibox-content user-panel p-t-none p-b-none"><p><small><strong>Group Description:</strong><br /><%= @group.description %></small></p></div>
			<% end %>
			<% if current_page?(group_path) %>
				<% if current_user %>
					<% if @current_member %>
						<% if @current_member.role == "admin" || @current_member.role == "moderator" || @current_member.role == "member"  %>
						<div class="ibox-content user-panel"><button id="js-add-post-button" class="btn btn-block btn-primary"><i class="fa fa-plus fa-fw"></i> Add Group Post</button></div>
						<% end %>
						<% if @current_member.role == "member"  %>
						<div class="ibox-content user-panel p-t-none">
							<%= link_to group_members_path(@group), class: "btn btn-white btn-sm btn-block m-t-none" do %>
							<i class="fa fa-users fa-fw"></i> View Members
							<% end %>
						</div>
						<% end %>
					<% end %>
				<% end %>
			<% else %>
				<div class="ibox-content user-panel"><%= link_to "Back to group page", group_path(@group.id), class: "btn btn-primary btn-block" %></div>
			<% end %>
			
			<% if current_user.admin_this_group?(@group) %>
				<div class="ibox-content ibox-heading">
					<h4>Group Admin Controls</h4>
						<%= link_to 'Manage Members', group_members_path(@group), class: "btn btn-primary btn-sm m-t-sm" %>
						<%= link_to 'Edit Group', edit_group_path(@group), class: "btn btn-primary btn-sm m-t-sm" %>
				</div>
			<% else %>
				<%= render 'join_buttons' %>
			<% end %>

			<div class="media-counts">
              <div class="media-friend-count"><%= pluralize((@group.regular_users.count + @group.moderators.count + @group.admins.count), 'Member') %></div>
              <div class="media-post-count"><%= pluralize(@group.group_posts.count, 'Post') %></div>
              <div class="clearfix"></div>
      </div>

</div>

app/views/groups/_group_members.html.erb
<div class="user-row <%= cycle('even', 'odd') -%>">
    <div class="col-md-6">
      <div class="pull-left">
        <%= link_to user_path(user.username) do %>
          <% if user.avatar.present? %>
            <%= image_tag(user.avatar_url(:friendship), class: "img-rounded grey-border") %>
          <% else %>
            <div class="default-friendship-icon <%= color_length(user.first_name.length) %>"><%= user.first_name.chars.first.titlecase + user.last_name.chars.first.titlecase %></div>
          <% end %>
        <% end %>
      </div>
      <div class="search-body">
        <div class="name m-t-xs">
          <%= link_to user_path(user.username) do %>
            <% if user.first_name.present? %>
              <%= user.first_name %> <%= user.last_name %>
            <% else %>
              <%= user.username %>
            <% end %>
          <% end %>
        </div>
        <div class="location m-b-xs">
            <% if user.city.present? || user.state.present? || user.country.present? %>
            <% else %>
              No Location Given
            <% end %>
            <% if user.city.present? %>
              <%= user.city %><% end %><% if user.state.present? %>, <%= user.state %>
            <% end %>
        </div>
      </div>
    </div>
      <div class="col-md-6">
        <% if current_user %>
          <span class="pull-right m-t-sm action-button-for-<%= user.id %>">
          <% if current_user == user %>
            <p>This is you.</p>
          <% else %>
              <%= action_buttons(user) %>
            <% if current_user.friendship_status(user) == "friends" %>
            <span id="js-subscription-btns-for-<%= user.id %>">
              <% if current_user.subscription_status(user) == "subscribed" %>
                <%= link_to "Email On", subscription_path(current_user.get_subscription(user)), method: :delete, :remote => true, class: "js-subscribed-btn btn btn-gold btn-sm m-l-sm" %>
              <% else %>
                <%= link_to "Email Off", subscriptions_path(subscribe_to_id: user), method: :post, :remote => true, class: "js-not-subscribed-btn btn btn-white btn-sm m-l-sm" %>
              <% end %>
            </span>
            <% end %>
          </span>
        <% end %>
        <% end %>
      </div>
          <div class="clearfix"></div>
  </div>
  

app/views/groups/_join_buttons.html.erb
<div class="ibox-content">
	<hr class="m-t-none m-b-sm"/>
		<strong>Group Membership</strong>
		<p><small>
			You are currently
			<% if @current_member && @current_member.role != "pending" %>
				a member
			<% else %>
				not a member
			<% end %>
			of this
			<% if @group.privacy == "Private" %>
				<strong>private</strong>
			<% else %>
				<strong>public</strong>
			<% end %>
			group.
			</small>
		</p>




<% if current_user && @current_member %>
	<% if current_user.admin_this_group?(@group) || current_user.moderate_this_group?(@group) %>
		<% if @group.admins.count == 1 %>
			<%# Only Admin User %>
		<% else %>
			<%# Not Only Admin User %>
			<%= button_to 'Stop being Admin and Leave Group', group_group_member_path(@group, @current_member), method: :delete, :class => "btn btn-warning btn-block" %>
		<% end %>
	<% else %>
		<% if @current_member.role == "pending" %>
			
					<small>You sent a join request to this group <%= time_ago_in_words(@current_member.created_at) %> ago.</small>	
					<%= button_to 'Cancel Join Request', group_group_member_path(@group, @current_member), method: :delete, :class => "btn btn-warning btn-sm m-t-sm" %>

		<% else %>
			<%= button_to 'Leave Group', group_group_member_path(@group, @current_member), method: :delete, :class => "btn btn-white btn-sm" %>
		<% end %>
	<% end %>
<% else %>
	<% if @group.privacy == "Public" %>
		<%= button_to 'Join Group', group_group_members_path(@group), :class => "btn btn-primary btn-sm" %>
	<% else %>
		<%= button_to 'Send Join Request', group_group_members_path(@group), :class => "btn btn-primary btn-sm" %>
	<% end %>
<% end %>
<% if @current_member && @current_member.role != "pending" %>
	<hr class="m-t-sm m-b-sm"/>
		<strong>Group Email Notify</strong>
		<p><small>
			You are currently
			<% if @current_member.email_notify == false %>
				not receiving
			<% else %>
				receiving
			<% end %>
			emails when a member posts to this group.
		</small></p>
	<% if @current_member.email_notify == false %>
		<%= link_to "Turn On Email Notify", email_notify_on_path(@group, @current_member), method: :put, class: 'btn btn-sm btn-primary' %>
	<% else %>
	<%= link_to "Turn Off Email Notify", email_notify_off_path(@group, @current_member), method: :put, class: 'btn btn-sm btn-primary' %>
	<% end %>
<% end %>
</div>

app/views/groups/_member.html.erb
<div class="user-row <%= cycle('even', 'odd', name: 'member') %>">
	<div class="col-sm-6">
		<div class="pull-left">
			<%= link_to user_path(member.user.username) do %>
			<% if member.user.avatar.friendship.present? %>
			<%= image_tag(member.user.avatar_url(:friendship), class: "img-rounded grey-border") %>
			<% else %>
			<div class="default-friendship-icon <%= color_length(member.user.first_name.length) %>"><%= member.user.first_name.chars.first.titlecase + member.user.last_name.chars.first.titlecase %></div>
			<% end %>
			<% end %>
		</div>
		<div class="search-body">
			<div class="name m-t-xs">
				<%= link_to user_path(member.user.username) do %>
				<% if member.user.first_name.present? %>
				<%= member.user.first_name %> <%= member.user.last_name %>
				<% else %>
				<%= member.user.username %>
				<% end %>
				<% end %>
			</div>
			<div class="location m-b-xs">
				<% if member.user.city.present? || member.user.state.present? %>
				<% else %>
				No Location Given
				<% end %>
				<% if member.user.city.present? %>
				<%= member.user.city %><% end %><% if member.user.state.present? %>, <%= member.user.state %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<% if current_user %>
		<span class="pull-right m-t-sm action-button-for-<%= member.user.id %>">
			<% if current_user == member.user %>
			<p>This is you.</p>
			<% else %>
			<%# action_buttons(member.user) %>
			<% if current_user.admin_this_group?(@group) || current_user.moderate_this_group?(@group) %>

				<div class="pull-right dropdown">
				<button class="dropdown-toggle btn-white" data-toggle="dropdown" aria-expanded="false">
					<i class="fa fa-angle-down"></i>
				</button>
				<ul class="dropdown-menu m-t-xs">
				<% if current_user.admin_this_group?(@group) %>
					<% if member.role != "admin" %>
						<li>
							<%= link_to make_admin_path(@group, member.id), method: :put do %>
								Make <%= member.user.first_name %> an Administrator
							<% end %>
						</li>
					<% end %>
				<% end %>
				<% if member.role != "moderator" %>
					<li>
						<%= link_to make_moderator_path(@group, member.id), method: :put do %>
							Make <%= member.user.first_name %> a Moderator
						<% end %>
					<li>
				<% end %>
				<% if member.role != "member" %>
					<li>
						<%= link_to make_member_path(@group, member.id), method: :put do %>
							Make <%= member.user.first_name %> a Group Member
						<% end %>
					</li>
				<% end %>
				<% if member.role == "pending" %>
					<li>
						<%= link_to reject_member_path(@group, member.id), method: :delete, data: { confirm: 'Are you sure you want to delete this group member?', :'confirm-button-text' => 'Delete', :'cancel-button-text' => 'Cancel', :'confirm-button-color' => '#EFA039'} do %>
							Reject membership request
						<% end %>
					</li>
				<% end %>
				<% if member.role == "member" || member.role == "moderator" %>
					<li>
						<%= link_to ban_member_path(@group, member.user.id), method: :delete, data: { confirm: 'Are you sure you want to delete this group member?', :'confirm-button-text' => 'Delete', :'cancel-button-text' => 'Cancel', :'confirm-button-color' => '#EFA039'} do %>
							Remove <%= member.user.first_name %> from group
						<% end %>
					</li>
				<% end %>
				</ul>
			</div>
		<% end %>
		</span>
		<% end %>
		<% end %>
	</div>
	<div class="clearfix"></div>
</div>

app/views/groups/edit.html.erb
<div class="row wrapper border-bottom page-heading m-b-lg">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2>Edit Group Profile</h2>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Current Group Image</h5>
				</div>
				<div class="ibox-content user-panel">
					<div class="pull-left">
						<% if @group.image.profile.present? %>
							<%= image_tag(@group.image_url(:profile).to_s, class: "img-rounded grey-border") %>
						<% else %>
							<div class="default-profile-icon <%= color_length(@group.name.length) %> grey-border"><i class="fa fa-users fa-fw font-awesome-profile-icon"></i></div>
						<% end %>
					</div>
					<div class="edit-image-btn">
						<div class="image-action m-l-lg">
							<%= link_to "Change Image", group_upload_path(@group), class: "btn btn-sm btn-primary" %>
							<% if @group.image.profile.present? %>
              <%= link_to "Remove Image", group_image_remove_path, class: "btn btn-white btn-xs m-t-sm" %>
            <% end %>
            <%= link_to "Back To Group", group_path(@group), class: "btn btn-white btn-xs m-t-sm" %>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Delete This Group</h5>
				</div>
				<div class="ibox-content user-panel">
				<p>Done with this group and want to remove it from the site?</p>
			<%= link_to 'Delete This Group', group_path(@group), method: :delete, data: { confirm: 'Are you sure you want to delete this group? This cannot be undone.', :'confirm-button-text' => 'Delete Group', :'cancel-button-text' => 'Cancel', :'confirm-button-color' => '#EFA039' }, class: "btn btn-white btn-sm" %>
				</div>
			</div>
		</div>
		<div class="col-md-9">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
				<h5>Edit Group Form</h5>
				</div>
				<div class="ibox-content no-side-borders">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/groups/index.html.erb
<div class="row wrapper page-heading m-b-lg">
  <div class="container">
  	<div class="row">
	    <div class="col-lg-12">
	      <h2>Groups</h2>
	    </div>
	  </div>
  </div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<%= render 'partials/group_box' %>
			<%= render 'partials/ads' %>
		</div>
		<div class="col-md-9">
			<%= render 'partials/groups_sub_nav' %>
	<% if params[:query].present? %>
		<h3 class="text-center m-t-lg"><%= pluralize(@groups.size, 'search result') %> found for: "<%= params[:query] %>"</h3>
	<% else %>
		<h3 class="text-center m-t-lg">Newest Groups</h3>
	<% end %>
		<div class="ibox float-e-margins">
      <div class="ibox-content user-panel search-user-panel m-t-none p-t-none">
				<% if @groups.present? %>
					<%= render @groups %>
				<% else %>
					<div style="padding: 16px;"><h5>There are no groups containing the term(s): <b><%= params[:query] %></b>.</h5></div>
				<% end %>
			</div>
		</div>
		<%= paginate @groups %>
	</div>
</div>
</div>

app/views/groups/new.html.erb
<div class="row wrapper page-heading m-b-lg">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2>Create A Group</h2>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
				<h5>Creating A Group</h5>
				</div>
				<div class="ibox-content no-side-borders">
					<p>When you create a group you will be setup as the administrator. Every group must have an administrator.</p>
					<p></p>
				</div>
			</div>

			<%if (current_user.subscription_plan == "Individual_Monthly" || current_user.subscription_plan == "Individual_Annual") %>
			<div class="ibox float-e-margins">
				<div class="ibox-title">
				<h5>Individual Supporter</h5>
				</div>
				<div class="ibox-content no-side-borders">
					<p>You are currently subscribed as an Individual Supporter. You can create and administrate up to <strong>3</strong> groups. You currently have <strong><%= @count %></strong>.</p>
				</div>
			</div>
			<% elsif (current_user.subscription_plan == "Organization_Monthly" || current_user.subscription_plan == "Organization_Annual") %>
				<div class="ibox float-e-margins">
				<div class="ibox-title">
				<h5>Organizational Supporter</h5>
				</div>
				<div class="ibox-content no-side-borders">
					<p>You are currently subscribed as an Organizational Supporter. You can create and administrate up to <strong>20</strong> groups. You currently have <strong><%= @count %></strong>.</p>
				</div>
			</div>
			<% end %>


		</div>
		<div class="col-md-9">
			<%= render 'partials/groups_sub_nav' %>
			<% if current_user.subscription_plan.blank? && (@count >= 1) %>
				<div class="ibox float-e-margins m-t-lg">
					<div class="ibox-content no-side-borders">
						You've reached your limit of creating and administrating <strong>1</strong> group as a non-supporting member. <%= link_to "Please ugrade", support_path %> if you need to create more groups.
					</div>
				</div>
			<% elsif (current_user.subscription_plan == "Individual_Monthly" || current_user.subscription_plan == "Individual_Annual") && @count >= 3 %>
				<div class="ibox float-e-margins m-t-lg">
					<div class="ibox-content no-side-borders">
						You've reached your limit of creating and administrating <strong>3</strong> groups as an Individual Member. <%= link_to "Please ugrade", support_path %> to Organization level support if you need to create more than 3 groups.
					</div>
				</div>
			<% elsif (current_user.subscription_plan == "Organization_Monthly" || current_user.subscription_plan == "Organization_Annual") && @count >= 20 %>
				<div class="ibox float-e-margins m-t-lg">
					<div class="ibox-content no-side-borders">
						You've reached your limit of creating and administrating <strong>20</strong> groups as an Organizational Supporter. <%= link_to "Please contact us", contact_path %> if you need to create and administrate more groups.
					</div>
				</div>
			<% else %>
				<h3 class="text-center m-t-lg">Create A Group</h3>

				<div class="ibox float-e-margins">
					<div class="ibox-title">
					<h5>Create A Group Form</h5>
					</div>
					<div class="ibox-content no-side-borders">
						<%= render 'form' %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('[data-toggle="popover"]').popover().click(function(event){event.preventDefault();})
	});
</script>