config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  
  root 'static#home'
	
	get 'users/upload'      => 'users#upload'
  post 'users/crop'       => 'users#crop'
  get 'users/crop'        => 'users#crop'
  get 'users/remove'      => 'users#remove'
  get 'users/:id/friends', to: 'users#friends', as: 'friends'
	
	resources :users do 
		member do
			get 'lock_user'
			get 'unlock_user'
		end
	end
	
	resources :friendships, only: [:create, :destroy, :accept] do
		member do
			put :accept
		end
	end

	resources :posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "posts#upvote"
		end
	end

	resources :group_posts, only: [:create, :edit, :update, :destroy] do
		member do
			put "prayed" => "group_posts#upvote"
		end
	end

	get 	'groups/:id/upload'				=> 'groups#upload', as: 'group_upload'
  post  'groups/:id/crop'   			=> 'groups#crop', as: 'group_crop'
  get		'groups/:id/crop'					=> 'groups#crop'
  get		'groups/:id/image_remove'	=> 'groups#image_remove', as: 'group_image_remove'

	get '/groups/your_groups' => 'groups#your_groups'

  get '/groups/:id/members/', to: 'groups#members', as: 'group_members'
  put '/groups/:group_id/members/make_admin/:request_id', to: 'group_members#make_admin', as: 'make_admin'
  put '/groups/:group_id/members/make_member/:request_id', to: 'group_members#make_member', as: 'make_member'
  put '/groups/:group_id/members/make_moderator/:request_id', to: 'group_members#make_moderator', as: 'make_moderator'
  delete '/groups/:group_id/members/reject/:request_id', to: 'group_members#reject_member', as: 'reject_member'
  delete '/groups/:group_id/members/ban/:user_id', to: 'group_members#ban_member', as: 'ban_member'

  put '/groups/:group_id/members/email_notify_on/:request_id', to: 'group_members#email_notify_on', as: 'email_notify_on'
  put '/groups/:group_id/members/email_notify_off/:request_id', to: 'group_members#email_notify_off', as: 'email_notify_off'


  resources :groups do
    resources :group_posts
    resources :group_members
  end

  resources :conversations do
  	resources :messages
 	end

	resources :subscriptions, only: [:create, :destroy]

	resources :activities, only: [:index]

	# Used for Stripe Subscriptions
	post '/charge/individual', to: 'charges#create_individual'
	post '/charge/individual_annual', to: 'charges#create_individual_annual'
	post '/charge/organization', to: 'charges#create_organization'
	post '/charge/organization_annual', to: 'charges#create_organization_annual'
	delete '/charge/cancel', to: 'charges#cancel_subscription'

	get 'contact', 				to: 'contact#new', as: 'contact'
	post 'contact', 			to: 'contact#create'

	post 'invite', 				to: 'invite#create'
	post 'group_invite', 	to: 'group_invite#create'

	#Admin Pages
	get 'admin'					=> 'admin#index'
	get 'admin/users'		=> 'admin#users'
	get 'admin/groups'	=> 'admin#groups'
	get 'admin/ads'			=> 'admin#ads'
	
	resources :advertisements

  # Static Pages
  get 'privacy' 	=> 'static#privacy'
  get 'terms'   	=> 'static#terms'
 	get 'faq' 			=> 'static#faq'
 	get 'advertise' => 'static#advertise'
 	get 'blocked' 	=> 'static#blocked'
 	get 'support' 	=> 'static#support'
 	get 'welcome' 	=> 'static#welcome'

 	get "*any", via: :all, to: "errors#not_found"

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

	before_action :authenticate_user!

	def index
		@post = Post.new
		@user = current_user
		@users = current_user.active_friends
		@users.push(current_user)
		@advertisements = Advertisement.limit(3).order("RANDOM()")
		@groups = current_user.group_members.where.not(role: 'pending').limit(5)
		@activities = Kaminari.paginate_array(Post.where(user_id: @users).includes(:user).order('created_at DESC')).page(params[:page]).per(10)
	end

end

app/views/activities/_activity.html.erb
<div id="post-<%= post.id %>" class="social-feed-box">
	<% if post.user == current_user %>
		You
	<% else %>
		<%= post.user.first_name + " " + post.user.last_name %><
	<% end %>
About <%= time_ago_in_words(post.created_at) %> ago.<br />
<%= post.post_type %><br />
<%= post.content %><br />
<% if current_user && current_user == post.user %>
	<%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post_path(post), method: :delete %>
<% end %>
</div>



<% @activities.each do |activity| %>
						<% unless activity.trackable_type == "Friendship" && activity.owner == current_user %>
							<% if activity.trackable %>
								<% case activity.trackable_type when "Post" %>
									<div id="activity-<%= activity.id %>" class="social-feed-box">
										<% if activity.owner == current_user %>
											<%# Owner Is Current User %>
	                		<div class="pull-right social-action dropdown">
	                  		<button class="dropdown-toggle btn-white" data-toggle="dropdown" aria-expanded="false">
	                    		<i class="fa fa-angle-down"></i>
	                  		</button>
	                  		<ul class="dropdown-menu m-t-xs">
	                    		<li>
	                      		<%= link_to "Edit Post", edit_post_path(activity.trackable) %>
	                    		</li>
	                    		<li>
	                      		<%= link_to "Delete Post", post_path(activity.trackable), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
	                    		</li>
	                  		</ul>
	                		</div>
	                	<% else %>
	                		<%# Owner Is NOT Current User %>
                      <% if current_user.voted_for? activity %>
                      <div class="pull-right social-action">
                        <span class="btn btn-prayed-for btn-circle btn-xs no-cursor" data-toggle="tooltip" data-placement="left" title="You've already prayed for this">
                          <i class="fa fa-heart fa-fw"></i>
                        </span>
                      </div>
                      <% else %>
                        <div class="pull-right social-action btn-prayed-for-<%= activity.id %>">
                            <%= link_to upvote_activity_path(activity), :remote => true, method: :put, class: 'js-not-prayed-btn btn btn-pray-for btn-circle btn-xs' do %>
                              <i class="fa fa-heart fa-fw"></i>
                            <% end %>
                        </div>
                      <% end %>
	                	<% end %>
                <div class="social-avatar">
                	<div class="pull-left">
										<% if activity.owner.avatar.present? %>
											<%= image_tag(activity.owner.avatar_url(:timeline), class: "img-circle") %>
										<% else %>
											<%= image_tag(('coprayers/timeline-generic-user.jpg'), class: "img-circle") %>
										<% end %>
									</div>
									<div class="media-body">
										<% if activity.owner.first_name.present? %>
											<%= link_to user_path(activity.owner.username) do %>
												<%= activity.owner.first_name %> <%= activity.owner.last_name %>
											<% end %>
										<% else %>
											<%= link_to activity.owner.username, user_path(activity.owner.username) %>
										<% end %>
                    <small class="text-muted">
                    <% if activity.trackable.post_type == 'prayer' %>
											<span class="prayer-label">Prayer Request</span>
										<% else %>
											<span class="praise-label">Praise Report</span>
										<% end %>
                    <span class="dash">/</span> <%= time_ago_in_words(activity.created_at) %> ago <span class="dash">/</span> Prayed for <span class="prayer-count-for-<%= activity.id %>"><%= pluralize(activity.get_upvotes.size, 'time') %></span></small>
                      </div>
								</div>	
								<div class="social-body">
									<p><%= simple_format(activity.trackable.content) %></p>
								</div>
								</div>
								<% when "Friendship" %>

								<div id="activity-<%= activity.id %>" class="social-feed-box">
                  <div class="social-avatar">
                      <div class="pull-left">
                        <% if activity.owner.avatar.present? %>
											    <%= image_tag(activity.owner.avatar_url(:timeline), class: "img-circle") %>
											  <% else %>
											    <%= image_tag(('coprayers/timeline-generic-user.jpg'), class: "img-circle") %>
											  <% end %>
                      </div>
                      <div class="friend-body">
                        <% if activity.owner.first_name.present? %>
													<%= link_to user_path(activity.owner.username) do %>
														<%= activity.owner.first_name %> <%= activity.owner.last_name %>
													<% end %>
												<% else %>
													<%= link_to activity.owner.username, user_path(activity.owner.username) %>
												<% end %>
												<small>is now friends with</small>
												<% if activity.recipient.first_name.present? %>
													<%= link_to user_path(activity.recipient.username) do %>
														<%= activity.recipient.first_name %> <%= activity.recipient.last_name %>
													<% end %>
												<% else %>
													<%= link_to activity.recipient.username, user_path(activity.recipient.username) %>
												<% end %>
												<% if activity.recipient.avatar.present? %>
													<%= image_tag(activity.recipient.avatar_url(:timeline), class: "img-circle") %>
												<% else %>
													<%= image_tag(('coprayers/timeline-generic-user.jpg'), class: "img-circle") %>
												<% end %>
                        <div class="clearfix"></div>
                      </div>
                    </div>
                </div>
								<% end %>
							<% end %>
						<% end %>
			
		<% end %>

app/views/activities/index.html.erb
<div class="row wrapper page-heading m-b-lg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2>Your Timeline</h2>
      </div>
    </div>
  </div>
</div>
<div class="container">

  <div class="row">
   <div class="col-md-3">
   <%= render 'partials/box_user' %> 
  <button id="js-add-post-button" class="btn btn-block btn-primary btn-lg"><i class="fa fa-plus fa-fw"></i>Add Post</button>
  <%= render 'partials/box_site_supporter' %>
  <div class="visible-xs m-t-lg"></div>
  <%= render 'partials/box_groups' %>

  <%= render 'partials/box_friends' %>

  <%= render 'partials/ads' %>

</div>
<div class="col-md-9">
  <%= render 'posts/form' %>
  <% if @user.sign_in_count == 1 %>
    <%= render 'partials/first_time_message' %>
  <% end %>
  

  <%= render @activities %>

  <%= paginate @activities %>
</div>
</div>
<script type="text/javascript">
$(document).ready(function() { 
  $("#js-add-post-form").hide();
});

  $("#js-add-post-button").click(function(){
    $("#js-add-post-form").slideDown("slow");
});

  $("#js-cancel-post-button").click(function(){
    $("#js-add-post-form").slideUp("slow");
});
</script>